### ISSUE TITLE
BUG report：retrieval_test.py  name 'texts' is not defined

### ISSUE THREAD

**Issue by alei76** [ZhuiyiTechnology/simbert#1]
BUG report：retrieval_test.py  name 'texts' is not defined

def most_similar(text, topn=10):
    """检索最相近的topn个句子
    """
    token_ids, segment_ids = tokenizer.encode(text, max_length=maxlen)
    vec = encoder.predict([[token_ids], [segment_ids]])[0]
    vec /= (vec**2).sum()**0.5
    sims = np.dot(vecs, vec)
    return [(texts[i], sims[i]) for i in sims.argsort()[::-1][:topn]]

**Comment by ZhuiyiTechnology** [comment]
是我的疏忽，已经修复
